// User states
const USER_STATES = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED'
};

// User roles
const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

// Wallet states
const WALLET_STATES = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
  CLOSED: 'CLOSED'
};

// Transaction types
const TRANSACTION_TYPES = {
  DEPOSIT: 'DEPOSIT',
  WITHDRAW: 'WITHDRAW',
  TRANSFER: 'TRANSFER'
};

// Transaction states
const TRANSACTION_STATES = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

// Movement types
const MOVEMENT_TYPES = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
};

// HTTP status codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

// Error codes
const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  WALLET_BLOCKED: 'WALLET_BLOCKED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  TRANSFER_TO_SELF: 'TRANSFER_TO_SELF',
  TRANSFER_TO_BLOCKED: 'TRANSFER_TO_BLOCKED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

module.exports = {
  USER_STATES,
  USER_ROLES,
  WALLET_STATES,
  TRANSACTION_TYPES,
  TRANSACTION_STATES,
  MOVEMENT_TYPES,
  HTTP_STATUS,
  ERROR_CODES
};
